name: Hello Workflow
on:
  push:
    branches:
      - main
jobs:      
  conditional:
    runs-on: ubuntu-latest
    steps:
      - name: Print Messege
        run: echo "this slays runs"
      - name: Run only on success
        if: seccess()
        run: echo "Previous step passed"






