name: Hello Workflow
on:
  push:
    branches:
      - main
jobs1:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Greet
        run: echo "Hello from step 1"
jobs2:
  runs-on: ubuntu-latest
  steps:
  -name: Job 2 step
   run: echo "This is Job 2"
        
